---
# tasks file for roles/environ
- name: Install aptitude package
  apt:
    pkg: aptitude
    state: present

- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install language-pack-ja package
  apt:
    pkg: language-pack-ja

- name: Check whether default locale is ja_JP.UTF-8
  command: grep -q '^LANG=ja_JP.UTF-8$' /etc/default/locale
  register: is_default_locale_ja
  check_mode: no
  changed_when: no
  failed_when: is_default_locale_ja.rc not in [0,1]

- name: Set default LANG to ja_JP.UTF-8
  command: update-locale LANG=ja_JP.UTF-8
  when: is_default_locale_ja.rc != 0

- name: Add LANGUAGE env var to ~vagarnt/.bashrc
  lineinfile:
    dest: /home/vagrant/.bashrc
    line: 'export LANGUAGE=ja_JP:ja'

- name: Add TERM env var to ~vagarnt/.bashrc
  lineinfile:
    dest: /home/vagrant/.bashrc
    line: 'export TERM=xterm-256color'
  when: ansible_env.TERM != 'xterm-256color'
